version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: 09:00
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'dependabot(gomod): '
    labels:
      - M-dependabot
    groups:
      gomod-weekly:
        patterns:
          - '*'
  - package-ecosystem: cargo
    directory: /kona
    schedule:
      interval: weekly
      day: monday
      time: 09:00
      timezone: UTC
    commit-message:
      prefix: 'dependabot(cargo): '
    labels:
      - M-dependabot
      - F-deps
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    groups:
      cargo-weekly:
        patterns:
          - '*'
